### PR TITLE
#25 & #31

### PR DESCRIPTION
**Pull request by Mayuresh94**

### CODE REVIEW

**Comment by magwas** [comment]
I have resolved the conflicts for you.

**Comment by magwas** [comment]
There was another pull request which we have merged before yours. It contained a version of WorkRequestTestData with default constructor. As in your version the constructor needs a UserTestData, this broke com.kodekonveyor.work_request.open.OpenWorkRequestControllerTest.java

Please fix that by instantiating a UserTestData object and giving that as parameter of the constructor.

Do not forget to pull the changes from your remote branch before you do that.

**Comment by Mayuresh94** [comment]
I have fixed the issue with the constructor, but was unable to pull the reference. getting PM's conflict error.

**Comment by magwas** [comment]
testcases=2

**Pull request merged**
