### PR TITLE
Issue #34: Delete WorkRequest

### PR DESCRIPTION
**Pull request by Meenal2020**

### CODE REVIEW

**Comment by magwas** [comment]
updated the branch with latest develop. please sync.

**Comment by magwas** [comment]
branch updated, please pull

**Comment by Mayuresh94** [comment]
The production code was already in place for this task but, no test or test class related to it. So, behavior was implemented but not tested.

**Comment by magwas** [comment]
The first test in RevokeWorkRequestControllerValidationTest

**Comment by magwas** [comment]
updated again, please sync

**Comment by Meenal2020** [comment]
review comments incorporated

**Comment by magwas** [comment]
updated branch, please pull before push

**Comment by szirbucz** [comment]
testcases=1
please fill in https://docs.google.com/forms/d/e/1FAIpQLSdNMbUDPHp2CCbsKtx3qMDCGXIYmmRsjJoF201Xtl-xvb2llQ/viewform

**Pull request merged**
