### PR TITLE
Issue - 66

### PR DESCRIPTION
**Pull request by pthakkar02**
@magwas  Kindly review the pull request.

### CODE REVIEW

**Comment by magwas** [comment]
You have coverage miss. Just call me if you need help with it.

**Comment by pthakkar02** [comment]
I can see below errors in shippable:-
ERROR: mutation coverage miss at com.kodekonveyor.work_request.offer.OfferValidationUtil.validatePrice
ERROR: mutation coverage miss at com.kodekonveyor.webapp.RemoteAuthenticationFilter.doFilter

@magwas, I am not sure how to resolve this, Can you please help.

**Comment by pthakkar02** [comment]
@magwas 
I have resolved the conflicts. Please verify.

**Comment by magwas** [comment]
updated the branch with latest develop. please sync

**Comment by magwas** [comment]
testcases=1
please fill in https://docs.google.com/forms/d/e/1FAIpQLSdNMbUDPHp2CCbsKtx3qMDCGXIYmmRsjJoF201Xtl-xvb2llQ/viewform

**Pull request merged**
